export const BeachDATA = [
  { id: "1", title: "Bournemouth Beach" },
  { id: "2", title: "Boscombe Beach" },
  { id: "3", title: "Durley Chine Beach" },
  { id: "4", title: "Alum Chine Beach" },
  { id: "5", title: "Southbourne Beach" },
  { id: "6", title: "Fisherman’s Walk Beach" },
  { id: "7", title: "Sandbanks Beach" },
  { id: "8", title: "Hengistbury Head Beach" },
  { id: "9", title: "Avon Beach" },
  { id: "10", title: "Mudeford Sandbank" },
  { id: "11", title: "Highcliffe Beach" },
  { id: "12", title: "Canford Cliffs Beach" },
  { id: "13", title: "Branksome Chine Beach" },
  { id: "14", title: "Hamworthy Beach" },
  { id: "15", title: "Shell Bay Beach" },
  { id: "16", title: "Poole Beach" },
  { id: "17", title: "Lulworth Cove Beach" },
  { id: "18", title: "Durdle Door Beach" },
  { id: "19", title: "Studland Beach" },
  { id: "20", title: "Swanage Beach" },
];
